Update OpenStreetMap.md
I have removed 2 extra comma that cause an error when you cut and paste to command line
 
(base) >netconvert --osm-files latest.osm -o region-latest.net.xml --keep-edges.in-geo-boundary "-116.0458,50.2788,-113.0356,51.6265" --no-internal-links, --keep-edges.by-vclass passenger, --remove-edges.by-type highway.track,highway.services,highway.unsurfaced
Error: On processing option '--no-internal-links,':
 No option with the name 'no-internal-links,' exists.
Error: Could not parse commandline options.
Quitting (on error).